name: Jessica Stokes
description: 'Jessica Stokes is a software developer from Melbourne, Australia'
url: https://jessicastokes.net
highlighter: pygments
timezone: Australia/Melbourne
exclude: ['readme.md']
paginate: 12
paginate_path: /blog/page-:num/
permalink: /blog/:year/:month/:day/:title/
kramdown:
  input: GFM
accounts:
  email: hello@jessicastokes.net
  github: ticky
  gitlab: ticky
  twitter: ticky
hireable: true
