name: Jessica Stokes
description: 'Jessica Stokes is a 24 year old developer in Melbourne, Australia'
url: http://127.0.0.1:4000
pygments: true
timezone: Australia/Melbourne
exclude: ['readme.md']
paginate: 2
paginate_path: /blog/page-:num/
permalink: /blog/:year/:month/:day/:title/
kramdown:
  input: GFM
