name: Jessica Stokes
description: 'Jessica Stokes is a 24 year old developer in Melbourne, Australia'
url: https://jessicastokes.net
pygments: true
timezone: Australia/Melbourne
exclude: ['readme.md']
paginate: 5
paginate_path: /blog/page-:num/
permalink: /blog/:year/:month/:day/:title/
kramdown:
  input: GFM
accounts:
  email: hello@jessicastokes.net
  github: ticky
  gitlab: ticky
  twitter: ticky
